_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
BatchSize:
    value: 265
Epochs:
    value: 1
Momentum:
    value: 0.9
Pretrained:
    value: true
lr:
    value: 0.001
