DataLoader:
  BatchSize: 256
  num_workers: 8
  shuffle: True
  Transforms: False
  Path: '/workspace/'
  deepLake: False
  shuffle: False
  pin_memory: False
  persistent_workers: False

Train:
  Epoch: 10
  WandB: True

Model:
  Pretrained: True
  Debug: False
  Path: 'ResNet.pt'

Optimizer:
  lr: 0.001
  momentum: 0.9

Scheduler:
  step_size: 7
  gamma: 0.1