DataLoader:
  BatchSize: 256
  num_workers: 8
  shuffle: True
  Transforms: False

Train:
  Epoch: 10
  WandB: False

Model:
  Pretrained: True

Optimizer:
  lr: 0.001
  momentum: 0.9

Scheduler:
  step_size: 7
  gamma: 0.1