DataLoader:
  BatchSize: 256
  num_workers: 1
  shuffle: True
  Transforms: False
  Path: '/content/drive/MyDrive/Projects/data/nabirds/nabirds/images'
  deepLake: True
  shuffle: True
  pin_memory: False
  persistent_workers: False

Train:
  Epoch: 10
  WandB: False

Model:
  Pretrained: True
  Debug: False
  Path: '/content/drive/MyDrive/Projects/ResNet.pt'

Optimizer:
  lr: 0.001
  momentum: 0.9

Scheduler:
  step_size: 7
  gamma: 0.1